/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float * suma_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

	result = a + b;

	return &result;
}

float * resta_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

	result = a - b;

	return &result;
}

float * multiplicacion_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

	result = a * b;

	return &result;
}

float * division_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;
	//Evitamos divitir por 0
	if(b != 0)		
		result = a/b;

	return &result;
}

t_vector * sumavectores_1_svc(t_vector v_1, t_vector v_2, int n,  struct svc_req *rqstp)
{
	static t_vector  result;
	result.t_vector_len =v_1.t_vector_len;
	result.t_vector_val = malloc(v_1.t_vector_len*sizeof(float));
	for(int i = 0; i < v_1.t_vector_len;i++)
		result.t_vector_val[i] = v_1.t_vector_val[i] + v_2.t_vector_val[i];

	return &result;
}

t_vector * productoescalarvectores_1_svc(t_vector v, float escalar, int n,  struct svc_req *rqstp)
{
	static t_vector  result;

	result.t_vector_len =v.t_vector_len;
	result.t_vector_val = malloc(v.t_vector_len*sizeof(float));
	for(int i = 0; i < v.t_vector_len;i++)
		result.t_vector_val[i] = v.t_vector_val[i] * escalar;

	return &result;
}

t_vector * productovectorial_1_svc(t_vector v_1, t_vector v_2, int n,  struct svc_req *rqstp)
{
	static t_vector  result;

	result.t_vector_len =v_1.t_vector_len;
	result.t_vector_val = malloc(v_1.t_vector_len*sizeof(float));

	result.t_vector_val[0] = v_1.t_vector_val[1]*v_2.t_vector_val[2] - v_1.t_vector_val[2]*v_2.t_vector_val[1];
	result.t_vector_val[1] = v_1.t_vector_val[2]*v_2.t_vector_val[0] - v_1.t_vector_val[0]*v_2.t_vector_val[2];
	result.t_vector_val[2] = v_1.t_vector_val[0]*v_2.t_vector_val[1] - v_1.t_vector_val[1]*v_2.t_vector_val[0];
	

	return &result;
}
