/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static float *
_suma_1 (suma_1_argument *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(argp->a, argp->b, rqstp));
}

static float *
_resta_1 (resta_1_argument *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(argp->a, argp->b, rqstp));
}

static float *
_multiplicacion_1 (multiplicacion_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicacion_1_svc(argp->a, argp->b, rqstp));
}

static float *
_division_1 (division_1_argument *argp, struct svc_req *rqstp)
{
	return (division_1_svc(argp->a, argp->b, rqstp));
}

static t_vector *
_sumavectores_1 (sumavectores_1_argument *argp, struct svc_req *rqstp)
{
	return (sumavectores_1_svc(argp->v_1, argp->v_2, rqstp));
}

static t_vector *
_productoescalarvectores_1 (productoescalarvectores_1_argument *argp, struct svc_req *rqstp)
{
	return (productoescalarvectores_1_svc(argp->v, argp->escalar, rqstp));
}

static t_vector *
_productovectorial_1 (productovectorial_1_argument *argp, struct svc_req *rqstp)
{
	return (productovectorial_1_svc(argp->v_1, argp->v_2, rqstp));
}

static float *
_mediaaritmetica_1 (t_vector  *argp, struct svc_req *rqstp)
{
	return (mediaaritmetica_1_svc(*argp, rqstp));
}

static t_vector *
_fibonacci_1 (int  *argp, struct svc_req *rqstp)
{
	return (fibonacci_1_svc(*argp, rqstp));
}

static int *
_factorial_1 (int  *argp, struct svc_req *rqstp)
{
	return (factorial_1_svc(*argp, rqstp));
}

static float *
_logaritmobase_n_1 (logaritmobase_n_1_argument *argp, struct svc_req *rqstp)
{
	return (logaritmobase_n_1_svc(argp->numero, argp->base, rqstp));
}

static float *
_potencia_1 (potencia_1_argument *argp, struct svc_req *rqstp)
{
	return (potencia_1_svc(argp->base, argp->exponente, rqstp));
}

static void
calculadora_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		suma_1_argument suma_1_arg;
		resta_1_argument resta_1_arg;
		multiplicacion_1_argument multiplicacion_1_arg;
		division_1_argument division_1_arg;
		sumavectores_1_argument sumavectores_1_arg;
		productoescalarvectores_1_argument productoescalarvectores_1_arg;
		productovectorial_1_argument productovectorial_1_arg;
		t_vector mediaaritmetica_1_arg;
		int fibonacci_1_arg;
		int factorial_1_arg;
		logaritmobase_n_1_argument logaritmobase_n_1_arg;
		potencia_1_argument potencia_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA:
		_xdr_argument = (xdrproc_t) xdr_suma_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case RESTA:
		_xdr_argument = (xdrproc_t) xdr_resta_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case MULTIPLICACION:
		_xdr_argument = (xdrproc_t) xdr_multiplicacion_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacion_1;
		break;

	case DIVISION:
		_xdr_argument = (xdrproc_t) xdr_division_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _division_1;
		break;

	case SUMAVECTORES:
		_xdr_argument = (xdrproc_t) xdr_sumavectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_t_vector;
		local = (char *(*)(char *, struct svc_req *)) _sumavectores_1;
		break;

	case PRODUCTOESCALARVECTORES:
		_xdr_argument = (xdrproc_t) xdr_productoescalarvectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_t_vector;
		local = (char *(*)(char *, struct svc_req *)) _productoescalarvectores_1;
		break;

	case PRODUCTOVECTORIAL:
		_xdr_argument = (xdrproc_t) xdr_productovectorial_1_argument;
		_xdr_result = (xdrproc_t) xdr_t_vector;
		local = (char *(*)(char *, struct svc_req *)) _productovectorial_1;
		break;

	case MEDIAARITMETICA:
		_xdr_argument = (xdrproc_t) xdr_t_vector;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _mediaaritmetica_1;
		break;

	case FIBONACCI:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_t_vector;
		local = (char *(*)(char *, struct svc_req *)) _fibonacci_1;
		break;

	case FACTORIAL:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _factorial_1;
		break;

	case LOGARITMOBASE_N:
		_xdr_argument = (xdrproc_t) xdr_logaritmobase_n_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _logaritmobase_n_1;
		break;

	case POTENCIA:
		_xdr_argument = (xdrproc_t) xdr_potencia_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _potencia_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORA, CALCULADORA_VER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCULADORA_VER, calculadora_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCULADORA_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCULADORA_VER, calculadora_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCULADORA_VER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
