/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
t_vector rellenaVector(int n)
{
	t_vector v_aux;
	v_aux.t_vector_len = n;
	v_aux.t_vector_val = malloc(n*sizeof(float));
	printf("Empieza a rellenar el vector\n");
	for(int i = 0; i < n; i++)
	{
		scanf("%f",&v_aux.t_vector_val[i]);
	}
	printf("Rellenado \n");
	return v_aux;
		
}

void mostrarVector(t_vector* v)
{
	for(int i = 0; i < v->t_vector_len; i++)
	{
		printf("%f  ",v->t_vector_val[i]);
	}
}

float* calculadora_1(char *host, float argv1, char operador, float argv2)
{
	CLIENT *clnt;
	float * res;


#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_VER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	switch(operador)	//Dependiendo del operador que haya introducido el usuario se llamará a una función u otra
	{
		case '+':
			res = suma_1(argv1,argv2,clnt);
		break;
		case '-':
			res = resta_1(argv1,argv2,clnt);
		break;
		case 'x':
			res = multiplicacion_1(argv1,argv2,clnt);
		break;
		case '/':
			res = division_1(argv1,argv2,clnt);
		break;
		default:
			printf("El operando introducido no es válido\n");
			exit(1);
		break;
	}
	return res;

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

t_vector* calculadora_2(char *host, t_vector v_1, t_vector v_2, int n, float escalar,int operacion)
{
	CLIENT *clnt;
	t_vector * res;


#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_VER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

switch(operacion)
{
	case 1:
		res = sumavectores_1(v_1,v_2,n,clnt);
	break;
	case 2:
		res = productoescalarvectores_1(v_1,escalar,n,clnt);
	break;
	case 3:
		res = productovectorial_1(v_1,v_2,n,clnt);
	break;
}
	return res;

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host; //Puntero a char que almacena el nombre del servidor
	char operador; // Almaceno en un char el operador
	float arg1, arg2; //Argumentos de las operaciones 
	float* resultado; //Puntero a double donde se almacenarán las operaciones
	int opcion = 0,vectores = 0, op_aux = 0, n;
	char* entrada;
	host = argv[1];		  //Almaceno el nombre del servidor
	while( 1 == 1)
	{
		switch(opcion)
		{
			case 0:
				printf("¿Qué quieres hacer?\n");
				printf("1 - Operaciones básicas (+ - x /)\n");
				printf("2 - Operaciones con vectores\n");
				printf("3 - Acabar ejecución\n");
				int x;
				scanf("%i",&x);
				opcion = (int)x;
			break;
			case 1:
				
				printf("Introduce el operador (+,-,x,/) \n");
				scanf("%s",&operador);
				printf("Introduce el primer argumento de la operación básica a realizar\n");
				scanf("%f",&arg1);
				printf("Introduce el segundo argumento de la operación básica a realizar\n");
				scanf("%f",&arg2);

				resultado = calculadora_1 (host,arg1,operador,arg2);	//Realizo el calculo
				printf("%f %c %f = %f\n",arg1,operador,arg2,*resultado); //Muestro por pantalla el resultado
				opcion = 0;
			break;
			case 2:
				vectores = 1;
				while(vectores == 1)
				{
					switch(op_aux)
					{
						case 0:
							printf("¿Qué operación quieres hacer con vectores?\n");
							printf("1 - Suma de vectores\n");
							printf("2 - Producto de un escalar por un vector\n");
							printf("3 - Producto vectorial\n");
							printf("4 - Volver al menu\n");
							int y;
							scanf("%i",&y);
							op_aux = (int)y;
						break;

						case 1:
							
							printf("Introduce el tamaño de los vectores, ambos deben tener la misma longitud\n");
							int w;
							scanf("%d",&w);
							printf("Rellena el primer vector\n");
							t_vector v_1;
							v_1.t_vector_len = w;
							v_1.t_vector_val = malloc(w*sizeof(float));
							printf("Empieza a rellenar el vector\n");
							for(int i = 0; i < v_1.t_vector_len; i++)
							{
								scanf("%f",&v_1.t_vector_val[i]);
							}		
							
							printf("Rellena el segundo vector\n");
							t_vector v_2;
							v_2.t_vector_len = w;
							v_2.t_vector_val = malloc(w*sizeof(float));
							for(int i = 0; i < v_2.t_vector_len; i++)
							{
								scanf("%f",&v_2.t_vector_val[i]);
							}
							


							t_vector r;

							r.t_vector_val = malloc(w*sizeof(float));
							r.t_vector_len = w;

							r = *calculadora_2(host,v_1,v_2,w,0.0,1);

							printf("El vector suma es: \n");
							for(int i = 0; i < r.t_vector_len; i++)
							{
								printf("%f  ",r.t_vector_val[i]);
							}

							printf("\n");
							free(v_1.t_vector_val);
							free(v_2.t_vector_val);
							free(r.t_vector_val);
							op_aux = 0;
						break;

						case 2:
							printf("Introduce el tamaño del vector\n");
						
							scanf("%d",&w);
							printf("Rellena el vector\n");

							v_1.t_vector_len = w;
							v_1.t_vector_val = malloc(w*sizeof(float));
							for(int i = 0; i < v_1.t_vector_len; i++)
							{
								scanf("%f",&v_1.t_vector_val[i]);
							}

							printf("Introduce el escalar\n");
							float esc;
							scanf("%e",&esc);


							r.t_vector_val = malloc(w*sizeof(float));
							r.t_vector_len = w;

							r = *calculadora_2(host,v_1,v_1,w,esc,2);

							printf("El vector resultado es: \n");
							for(int i = 0; i < r.t_vector_len; i++)
							{
								printf("%f  ",r.t_vector_val[i]);
							}

							printf("\n");
							free(v_1.t_vector_val);
							free(r.t_vector_val);
							op_aux = 0;
						break;

						case 3:
							printf("El producto vectorial se hará de vectores de tamaño 3\n");
							printf("Rellena el primer vector\n");

							v_1.t_vector_len = 3;
							v_1.t_vector_val = malloc(3*sizeof(float));
							for(int i = 0; i < v_1.t_vector_len; i++)
							{
								scanf("%f",&v_1.t_vector_val[i]);
							}

							printf("Rellena el segundo vector\n");

							v_2.t_vector_len = 3;
							v_2.t_vector_val = malloc(3*sizeof(float));
							for(int i = 0; i < v_2.t_vector_len; i++)
							{
								scanf("%f",&v_2.t_vector_val[i]);
							}


							r = *calculadora_2(host,v_1,v_2,w,0.0,3);

							printf("El vector resultado es: \n");
							for(int i = 0; i < r.t_vector_len; i++)
							{
								printf("%f  ",r.t_vector_val[i]);
							}

							printf("\n");
							free(v_1.t_vector_val);
							free(v_2.t_vector_val);
							free(r.t_vector_val);

							op_aux = 0;
						break;

						case 4:
							vectores = 0;
							opcion = 0;
						break;
					}
				}
			break;

			case 3:
				exit(0);
			break;
		}
	}
}
